apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowess-deployment
spec:
  selector:
    matchLabels:
      app: PROWESS
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: PROWESS
    spec:
      hostNetwork: true
      containers:
      - image: prowess-db:latest
        name: prowess-db
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "my-secret-pw"
        args: ["--default-authentication-plugin=mysql_native_password"]
        imagePullPolicy: IfNotPresent
      - image: prowess-backend:latest
        name: prowess-backend
        ports:
        - containerPort: 3001
        imagePullPolicy: IfNotPresent

